name: Build webpack
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: echo NODE_ENV=production >> .env
      - run: echo ETH_NETWORK='goerli' >> .env
      - run: echo NETWORK='ethereum' >> .env
      - run: echo STARKWARE_APP='http://fossairdrop.com' >> .env
      - run: echo IPFS_HOST='fossairdrop.com' >> .env
      - run: echo INFURA_ID=secrets.INFURA_ID >> .env
      - run: npm install
      - run: npm run build
      - run: echo privatenfts.xyz >> ./dist/CNAME
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
